<?php

namespace ContainerM7Mpt6x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TC2yGzsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TC2yGzs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TC2yGzs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'proyecto' => ['privates', '.errored..service_locator.TC2yGzs.App\\Entity\\Proyectos', NULL, 'Cannot autowire service ".service_locator.TC2yGzs": it references class "App\\Entity\\Proyectos" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'proyecto' => 'App\\Entity\\Proyectos',
        ]);
    }
}
