<?php

namespace ContainerM7Mpt6x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KA0PUcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KA0_PUc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KA0_PUc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'proyecto' => ['privates', '.errored..service_locator.KA0_PUc.App\\Entity\\Proyectos', NULL, 'Cannot autowire service ".service_locator.KA0_PUc": it references class "App\\Entity\\Proyectos" but no such service exists.'],
        ], [
            'proyecto' => 'App\\Entity\\Proyectos',
        ]);
    }
}
