<?php

namespace ContainerM7Mpt6x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4iE8qmkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4iE8qmk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4iE8qmk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ProyectosController::delete' => ['privates', '.service_locator.TC2yGzs', 'get_ServiceLocator_TC2yGzsService', true],
            'App\\Controller\\ProyectosController::edit' => ['privates', '.service_locator.TC2yGzs', 'get_ServiceLocator_TC2yGzsService', true],
            'App\\Controller\\ProyectosController::index' => ['privates', '.service_locator.2eex2ln', 'get_ServiceLocator_2eex2lnService', true],
            'App\\Controller\\ProyectosController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ProyectosController::show' => ['privates', '.service_locator.KA0_PUc', 'get_ServiceLocator_KA0PUcService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ProyectosController:delete' => ['privates', '.service_locator.TC2yGzs', 'get_ServiceLocator_TC2yGzsService', true],
            'App\\Controller\\ProyectosController:edit' => ['privates', '.service_locator.TC2yGzs', 'get_ServiceLocator_TC2yGzsService', true],
            'App\\Controller\\ProyectosController:index' => ['privates', '.service_locator.2eex2ln', 'get_ServiceLocator_2eex2lnService', true],
            'App\\Controller\\ProyectosController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ProyectosController:show' => ['privates', '.service_locator.KA0_PUc', 'get_ServiceLocator_KA0PUcService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ProyectosController::delete' => '?',
            'App\\Controller\\ProyectosController::edit' => '?',
            'App\\Controller\\ProyectosController::index' => '?',
            'App\\Controller\\ProyectosController::new' => '?',
            'App\\Controller\\ProyectosController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ProyectosController:delete' => '?',
            'App\\Controller\\ProyectosController:edit' => '?',
            'App\\Controller\\ProyectosController:index' => '?',
            'App\\Controller\\ProyectosController:new' => '?',
            'App\\Controller\\ProyectosController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
