<?php

namespace ContainerM7Mpt6x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProyectosService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KA0_PUc.App\Entity\Proyectos' shared service.
     *
     * @return \App\Entity\Proyectos
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.KA0_PUc": it references class "App\\Entity\\Proyectos" but no such service exists.');
    }
}
